### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by fmu2** [gitter-lab/ml-bio-workshop#15]
Below is the error message:

Traceback (most recent call last):
  File "ml4bio.py", line 981, in finish_train
    self.push(model, 'val')
  File "ml4bio.py", line 1044, in push
    self.switch_model(row, 0)    # mark the new classifier as selected
  File "ml4bio.py", line 1116, in switch_model
    self.plot()
  File "ml4bio.py", line 1153, in plot
    self.curr_model.plot_decision_regions(option, self.canvas)
  File "/Users/xiangyangliu/Google Drive/Workshops/20180823 ML workshop/ml-bio-workshop-master/src/model.py", line 410, in plot_decision_regions
    ax = canvas.figure.subplots()
AttributeError: 'Figure' object has no attribute 'subplots'
Abort trap: 6

 

Below is the conda ls result:
 
# packages in environment at /anaconda/envs/ml4bio:
#
certifi                   2016.2.28                py35_0  
cycler                    0.10.0                   py35_0  
freetype                  2.5.5                         2  
icu                       54.1                          0  
libpng                    1.6.30                        1  
matplotlib                2.0.2               np113py35_0  
mkl                       2017.0.3                      0  
numpy                     1.13.1                   py35_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py35_0  
pip                       9.0.1                    py35_1  
pyparsing                 2.2.0                    py35_0  
pyqt                      5.6.0                    py35_2  
python                    3.5.4                         0  
python-dateutil           2.6.1                    py35_0  
pytz                      2017.2                   py35_0  
qt                        5.6.2                         2  
readline                  6.2                           2  
scikit-learn              0.19.0              np113py35_0  
scipy                     0.19.1              np113py35_0  
setuptools                36.4.0                   py35_1  
sip                       4.18                     py35_0  
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0

**Comment by fmu2** [comment]
The attribute 'subplots' was introduced in matplotlib 2.1. The conda environment uses 2.0.2.
See this post: https://github.com/matplotlib/matplotlib/issues/10855

**Comment by agitter** [comment]
Closed by ebab60488151de22f3ddee215e204402a2a9ea96.  I pinned the matplotlib version to 2.1.

This environment works on my Windows machine and the biostat server.  It failed on the older Linux server described in https://github.com/gitter-lab/ml-bio-workshop/issues/8#issuecomment-413741774.  However, I find this acceptable.  We need a version of matplotlib that the software can use.
