### ISSUE TITLE
Revise interactive activities

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ml-bio-workshop#42]
We could have partner activities so that one partner tries Version A and another tries Version B.  We could also provide printed handouts with specific questions for the interaction components.

**Comment by agitter** [comment]
One good idea would be to partner advanced and beginner participants.  We will not know how to identify them though if we keep the pre-workshop survey anonymous.

**Comment by cmilica** [comment]
Should we close this issue?

**Comment by agitter** [comment]
We can probably close it.  @csmagnano do you agree that our current version of the workshop addresses this?
