### ISSUE TITLE
Merging gh-pages and master

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ml-bio-workshop#73]
We are now enthusiastic about the transition to the Carpentries lesson format.  A good next step after our next pilot workshop will be to merge our two main branches to simplify maintenance and clean up the repository.

**Comment by agitter** [comment]
The [example lesson](https://github.com/carpentries/lesson-example) recommends keeping `gh-pages` as the default branch.  If we follow that example, we would merge material from `master` into `gh-pages` and then delete `master`.

Here is a sketch of how we could complete the merge:

| `master` branch content 	| Merge plan 	|
|-------------------------------	|----------------------------------------------------------------------	|
| `binder` 	| Keep subdirectory 	|
| `data` 	| Move into existing subdirectory 	|
| `figures` 	| Move into `fig` subdirectory, update attribution 	|
| `guide` 	| Temporarily keep subdirectory, ultimately want to render and display 	|
| `scripts` 	| Undecided, could move to `bin` 	|
| `.travis.yml` 	| Need to merge 	|
| `LICENSE.md`,`README.md` 	| Need to merge 	|
| `illustration.ipynb` 	| Keep file 	|
| Other `.md` and `.pptx` files 	| Keep files 	|

**Comment by cmilica** [comment]
This looks good to me!

**Comment by agitter** [comment]
Closed by 3ab5c6ac48f3e60f3d0bc593b3a3d5c444595ad9
