### ISSUE TITLE
Add a lesson introducing the ml4bio software

### ISSUE THREAD

**Issue by agitter** [gitter-lab/ml-bio-workshop#91]
We should invest more time early on giving a tour of the ml4bio software interface.  This can be separated as its own short lesson.  Participants need to be comfortable with the different steps, buttons, and overall workflow before they can successfully finish the later exercises.

This could also help address participant confusion about what options they need to know about and which, like the advanced validation options, they do not.

**Comment by cmilica** [comment]
Do we maybe just want to edit/change the title [to about page in Extras?](https://github.com/gitter-lab/ml-bio-workshop/blob/gh-pages/_extras/about.md)

**Comment by agitter** [comment]
We can reuse or keep a lot of this content.  I think the main goal of this recommendation was to budget time in the schedule and make an interactive lesson around the software.  We can use the same prompts and callouts to guide the interactive demonstration of the software.  The flow may be that we show them how to do something in the software and then they try it themselves.

**Comment by agitter** [comment]
Closed by #103
